version: '3.8'
services:
  linux:
    image: debian:latest
    container_name: linux
    stdin_open: true      # Keep stdin open for interactive use
    tty: true             # Allocate a pseudo-TT`Y
    volumes:
      - ./backup_root:/root  # Optional: Shared data folder
    ports:
      - "2222:22"          # Example: Map port 2222 for SSH if needed
    cap_add:
      - SYS_ADMIN   # Required for FUSE
    security_opt:
      - apparmor:unconfined  # Disable AppArmor restrictions (if needed)
    devices:
      - /dev/fuse 
    command: /bin/bash      # Start the container with a bash shell
