version: '3.8'
services:
  linux:
    image: debian:latest  # Replace 'ubuntu:latest' with any Linux distro you prefer
    container_name: my_linux_container
    stdin_open: true      # Keep stdin open for interactive use
    tty: true             # Allocate a pseudo-TT`Y
    volumes:
      - ./shared_data:/shared_data  # Optional: Shared data folder
    ports:
      - "2222:22"          # Example: Map port 2222 for SSH if needed
    command: /bin/bash      # Start the container with a bash shell
